version: '3.8'

services:
  web:
    build:
        context: ./pong_app
        dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/pong_app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    user: postgres
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/pong_app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: