version: '3.8'

services:
  web:
    build:
        context: ./pong_app
        dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/pong_app/web/staticfiles
      - media_volume:/home/pong_app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    user: postgres
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx_proxy:
    build: ./nginx_proxy
    volumes:
      - static_volume:/home/pong_app/web/staticfiles
      - media_volume:/home/pong_app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  
  nginx_frontend:
    build: ./front-end
    volumes:
      - ./front-end:/usr/share/nginx/html
      
    ports:
      - 80:80
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: