services:
  django_backend:
    build:
        context: ./py_backend/docker
        dockerfile: Dockerfile
    volumes:
       - staticfiles:/staticfiles
       - ./py_backend:/code
       - certificates:/etc/nginx/ssl  
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always


  db:
    image: postgres:latest
    user: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/app/
    volumes:
      - certificates:/etc/nginx/ssl  
      - staticfiles:/staticfiles
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - django_backend
    ports:
      - 8000:80
    restart: always
  
volumes:
  postgres_data:
  certificates:
  staticfiles: 