version: '3.8'

services:
  django-backend:
    build:
        context: ../py_backend/docker
        dockerfile: Dockerfile.dev
    volumes:
       - ../py_backend:/code
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - ./.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=pong_app
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx-frontend:
    # build: ../frontend/config
    image: nginx
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - 8081:80
    restart: always

volumes:
  db-data: